//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WikiCharity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialNew
    {
        public int Id { get; set; }
        public string ABN { get; set; }
        public string AccountInfo { get; set; }
        public Nullable<double> Donations { get; set; }
        public Nullable<double> EmpExpense { get; set; }
        public string ReportFrom { get; set; }
        public string ReportTo { get; set; }
        public Nullable<double> GoverGrant { get; set; }
        public Nullable<double> GDInAus { get; set; }
        public Nullable<double> GDOutAus { get; set; }
        public Nullable<double> NetAssets { get; set; }
        public Nullable<double> NetSurplus { get; set; }
        public Nullable<double> TotalAssets { get; set; }
        public Nullable<double> TotalCurrentAssets { get; set; }
        public Nullable<double> TotalCurrentLia { get; set; }
        public Nullable<double> Expense { get; set; }
        public Nullable<double> TotalGrossIncome { get; set; }
        public Nullable<double> TotalLia { get; set; }
        public Nullable<double> TotalNotCurrentAssets { get; set; }
        public Nullable<double> TotalNotCurrentLia { get; set; }
        public string FYear { get; set; }
        public Nullable<double> EmpExpensePersentage { get; set; }
        public Nullable<double> OtherIncome { get; set; }
        public Nullable<double> AllOtherExpense { get; set; }
        public Nullable<double> DebtEquityRadio { get; set; }
        public Nullable<double> SavingRadio { get; set; }
        public Nullable<double> CurrentRadio { get; set; }
        public Nullable<double> DebtRadio { get; set; }
        public Nullable<double> EmpExpInSizeMedian { get; set; }
        public Nullable<double> DebtEquityInSizeMedian { get; set; }
        public Nullable<double> SavingRadioInSizeMedian { get; set; }
        public Nullable<double> CurrentRadioInSizeMedian { get; set; }
        public Nullable<double> DebtRadioInSizeMedian { get; set; }
    }
}
